apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-app  # Correspond à l'étiquette utilisée dans le Deployment
  ports:
    - protocol: TCP
      port: 80  # Le port externe du service (accessible via le LoadBalancer)
      targetPort: 8084  # Le port interne où l'application Spring Boot écoute
